### ISSUE TITLE
Add Separate Files For Objects

### ISSUE THREAD

**Issue by azharzulkifli98** [redzic/chess-gui#1]
I like the way its designed but it could be easier to understand/maintain if you pulled out some stuff into their own files. I'm not too sure how its done in rust but for example lines 12 - 112 could be put into their own file of global const objects.

**Comment by redzic** [comment]
Thanks for the issue! I went ahead and made a module for all the piece-related code and their constants. Perhaps stuff like move generation and legality checking could be in their own files as well, and main.rs would just have the gui code.

**Comment by azharzulkifli98** [comment]
Ay nice! I was thinking the exact same thing, something like a logic.rs or rules.rs file
